### ISSUE TITLE
awd插件的问题

### ISSUE THREAD

**Issue by Dar1in9s** [D0g3-Lab/H1ve#15]
### 问题：
按照readme所给的步骤做，但是在初始化的时候出错了。
![image](https://user-images.githubusercontent.com/46131597/72326671-9481c080-36ea-11ea-8e82-38801bf77c26.png)

### 我的配置：
题目：
![image](https://user-images.githubusercontent.com/46131597/72327164-88e2c980-36eb-11ea-9fd4-361ffb956c9f.png)

插件：
![image](https://user-images.githubusercontent.com/46131597/72327190-926c3180-36eb-11ea-9c29-cb63225111f6.png)
这边是有那个镜像的，并且镜像可用
![image](https://user-images.githubusercontent.com/46131597/72327327-cc3d3800-36eb-11ea-849b-f8f2143d03c3.png)

### Version & Environment (系统/环境版本)
+ Docker版本：19.03.5
+ Docker-compose：1.23.1
+ Os Version：centos7

**Comment by 0akarma** [comment]
管理员是不能有比赛环境的，猜测是你没有创建普通用户或者普通队伍，配置是没有问题的

**Comment by Dar1in9s** [comment]
但是我创建了普通用户之后还是出现了相同的错误

**Comment by 0akarma** [comment]
如果是初始化比赛的时候出现这个报错，那就把比赛先删除了再初始化，应该就没问题了，还有就是记得配置比赛开始时间。

**Comment by Dar1in9s** [comment]
好的，感谢回答，我已经解决了这个问题

**Comment by longzhs** [comment]
别的功能都测试正常，用Glowworm插件做awd测试时开始出现同样的初始化报错，通过配置比赛开始时间解决了，但后面正常Run、StartCheck后发现提交flag值问题：普通用户challenge题目上提交错误的或自己队伍的flag值都有相应的出错提示，但提交别的组肯定正确flag值，单击submit后没有任何反应。。Scoreboard没有得分纪录。Centos7和Ubuntu18.04环境下同样的问题，请问可能的原因

**Comment by 0akarma** [comment]
> 普通用户challenge题目上提交错误的或自己队伍的flag值都有相应的出错提示，但提交别的组肯定正确flag值，单击submit后没有任何反应

提交别的组的flag你是从哪里看到的，是后台，还是队伍容器里面？
没有任何反应，`f12`看看请求发出没有，以及是否有报错。
因为没有反应，所以scoreboard没有记录是正常的。

**Comment by longzhs** [comment]
感谢回复。flag值是攻击容器靶机获取的，管理后台里看到的是同样的值。f12和burpsuite抓包发现提交正确flag值后返回的是500服务器错误。。测试使用的是自带的web_yunnan_simple和web_pyblog两个例子，镜像build不成功，是直接docker pull下来的。
![1](https://user-images.githubusercontent.com/22930220/73032003-b57bab80-3e78-11ea-8e50-e693d316841b.png)
![2](https://user-images.githubusercontent.com/22930220/73032012-bad8f600-3e78-11ea-9f30-9e7fe877b6d1.png)
![3](https://user-images.githubusercontent.com/22930220/73032014-bd3b5000-3e78-11ea-9c3e-ffa3a2857379.png)
![4](https://user-images.githubusercontent.com/22930220/73032155-36d33e00-3e79-11ea-8cf6-94d4c40161af.png)

**Comment by 0akarma** [comment]
看一下`.data/CTFd/logs/error.log`里的报错呢，这部分我没有做异常处理～
要看一下报错才能确定是哪部份出了问题，因为之前我自己测试的时候是没有问题的（

**Comment by longzhs** [comment]
error.log文件中出错部分提示：
[2020-01-23 21:57:03 +0000] [1] [INFO] Handling signal: winch
[2020-01-23 22:14:34,867] ERROR in app: Exception on /api/v1/challenges/attempt [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/bhs/H1ve/CTFd/utils/decorators/visibility.py", line 47, in _check_challenge_visibility
    return f(*args, **kwargs)
  File "/home/bhs/H1ve/CTFd/utils/decorators/__init__.py", line 21, in during_ctf_time_only_wrapper
    return f(*args, **kwargs)
  File "/home/bhs/H1ve/CTFd/utils/decorators/__init__.py", line 70, in _require_verified_emails
    return f(*args, **kwargs)
  File "/home/bhs/H1ve/CTFd/api/v1/challenges.py", line 434, in post
    user=user, team=team, challenge=challenge, request=request
  File "/home/bhs/H1ve/CTFd/plugins/ctfd_glowworm/models.py", line 209, in solve
    team_id = victim_name.team_id
AttributeError: 'Teams' object has no attribute 'team_id'
[2020-01-23 22:50:52,544] ERROR in app: Exception on /api/v1/challenges/attempt [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/bhs/H1ve/CTFd/utils/decorators/visibility.py", line 47, in _check_challenge_visibility
    return f(*args, **kwargs)
  File "/home/bhs/H1ve/CTFd/utils/decorators/__init__.py", line 21, in during_ctf_time_only_wrapper
    return f(*args, **kwargs)
  File "/home/bhs/H1ve/CTFd/utils/decorators/__init__.py", line 70, in _require_verified_emails
    return f(*args, **kwargs)
  File "/home/bhs/H1ve/CTFd/api/v1/challenges.py", line 434, in post
    user=user, team=team, challenge=challenge, request=request
  File "/home/bhs/H1ve/CTFd/plugins/ctfd_glowworm/models.py", line 209, in solve
    team_id = victim_name.team_id
AttributeError: 'Teams' object has no attribute 'team_id'
[2020-01-23 23:08:32 +0000] [1] [INFO] Handling signal: winch
[2020-01-23 23:08:32 +0000] [1] [INFO] Handling signal: winch
有空帮看看问题出在哪儿，辛苦了！

**Comment by 0akarma** [comment]
```
File "/home/bhs/H1ve/CTFd/plugins/ctfd_glowworm/models.py", line 209, in solve
team_id = victim_name.team_id
AttributeError: 'Teams' object has no attribute 'team_id'
```
你把`models.py` 209行改成`team_id = victim_name.id`试试看

**Comment by longzhs** [comment]
改了，还是出错：
 File "/home/bhs/H1ve/CTFd/plugins/ctfd_glowworm/models.py", line 209, in solve
    team_id = victim_name.id
AttributeError: 'Teams' object has no attribute 'team_id'

**Comment by longzhs** [comment]
发现：只在team团队模式下出错。将网站reset改成user用户模式后，AWD评分正常了。

**Comment by longzhs** [comment]
另外，似乎以前每轮check检查正常的AWD题目，重新run启用后就都通不过检查了。提示：
<GlowwormAttacks (transient 139684914484176)>
<Submission None, 1, 127.0.0.1, Team6_web_yunnan_simple seems down.>

**Comment by 0akarma** [comment]
> 改了，还是出错：
> File "/home/bhs/H1ve/CTFd/plugins/ctfd_glowworm/models.py", line 209, in solve
> team_id = victim_name.id
> AttributeError: 'Teams' object has no attribute 'team_id'

这个我改了是没有问题的，你改了之后要重启一下容器才可以

**Comment by 0akarma** [comment]
> 另外，似乎以前每轮check检查正常的AWD题目，重新run启用后就都通不过检查了。提示：
> <GlowwormAttacks (transient 139684914484176)>
> <Submission None, 1, 127.0.0.1, Team6_web_yunnan_simple seems down.>

check的逻辑应该是没问题的，你直接访问一下，看下网站能不能访问就好了。
如果你卡在整点重新run的话，他启动需要时间，所以就会出现这种情况。

**Comment by longzhs** [comment]
好的，问题都解决了，非常感谢！

**Comment by Yaoisss** [comment]
containers key 是什么意思?是我环境的密码还是docker的?

**Comment by 0akarma** [comment]
> containers key 是什么意思?是我环境的密码还是docker的?

[Containers Key 填写 docker 虚拟机内 root 用户的密码](https://h1ve.dao.ge/guide/ctfd-glowworm.html#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE)

**Comment by Yaoisss** [comment]
这个root密码我没有，是h1ve虚拟机的密码吗?

**Comment by Yaoisss** [comment]
h1ve-main这虚拟机吗?

**Comment by Yaoisss** [comment]
还有frp用的是80端口，我需要更改，才能让web_yunnan_simple  运行起来吗?
