### ISSUE TITLE
redis.exceptions.ConnectionError: max number of clients reached

### ISSUE THREAD

**Issue by bjrjk** [D0g3-Lab/H1ve#22]
### New Issue Checklist (自检清单)

- [Y] Updated H1ve to the latest version (是否更新到最新版本)
- [Y] I have read the [README](https://github.com/D0g3-Lab/H1ve/blob/master/README.md)
- [Y] I searched for [existing GitHub issues](https://github.com/D0g3-Lab/H1ve/issues)

### Issue Description (问题描述)

服务器使用一段时间后会出现500问题，查看ErrorLog典型错误如下：
```
[2020-03-16 11:00:43,372] ERROR in app: Exception on /themes/H1ve-theme/static/img/favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 755, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 768, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 636, in read_response
    raise e
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 633, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 308, in read_response
    raise error
redis.exceptions.ConnectionError: max number of clients reached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2291, in wsgi_app
    ctx.push()
  File "/usr/local/lib/python3.7/site-packages/flask/ctx.py", line 377, in push
    self.app, self.request
  File "/home/ec2-user/H1ve/CTFd/utils/sessions/__init__.py", line 66, in open_session
    val = cache.get(self.key_prefix + sid)
  File "/usr/local/lib/python3.7/site-packages/flask_caching/__init__.py", line 233, in get
    return self.cache.get(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/contrib/cache.py", line 631, in get
    return self.load_object(self._client.get(self.key_prefix + key))
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1207, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 761, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 768, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 636, in read_response
    raise e
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 633, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 308, in read_response
    raise error
redis.exceptions.ConnectionError: max number of clients reached
[2020-03-16 11:00:43,533] ERROR in app: Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 755, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 768, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 636, in read_response
    raise e
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 633, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 308, in read_response
    raise error
redis.exceptions.ConnectionError: max number of clients reached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2291, in wsgi_app
    ctx.push()
  File "/usr/local/lib/python3.7/site-packages/flask/ctx.py", line 377, in push
    self.app, self.request
  File "/home/ec2-user/H1ve/CTFd/utils/sessions/__init__.py", line 66, in open_session
    val = cache.get(self.key_prefix + sid)
  File "/usr/local/lib/python3.7/site-packages/flask_caching/__init__.py", line 233, in get
    return self.cache.get(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/contrib/cache.py", line 631, in get
    return self.load_object(self._client.get(self.key_prefix + key))
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1207, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 761, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 768, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 636, in read_response
    raise e
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 633, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 308, in read_response
    raise error
redis.exceptions.ConnectionError: max number of clients reached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1833, in finalize_request
    response = self.process_response(response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2114, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/home/ec2-user/H1ve/CTFd/utils/sessions/__init__.py", line 80, in save_session
    if session.modified:
AttributeError: 'NoneType' object has no attribute 'modified'

```
### Version & Environment (系统/环境版本)
+ Docker Version: Docker version 17.03.2-ce, build f5ec1e2
+ Docker-compose Version: docker-compose version 1.25.4, build unknown
+ Os Version: Amazon Linux 2 AMI

**Comment by 0akarma** [comment]
建议出现这种情况的时候进redis容器查看当前连接数`redis-cli info | grep connected_clients`与系统最大`max open files`数，如`max open files`已改大仍出现这种情况，建议修改redis连接超时时间`CONFIG SET timeout 60`

**Comment by bjrjk** [comment]
谢谢
