### ISSUE TITLE
h1ve_main_1 exited with code 1

### ISSUE THREAD

**Issue by brownfoxsir** [D0g3-Lab/H1ve#27]
- [x] Updated H1ve to the latest version 
- [x] I have read the [README](https://github.com/D0g3-Lab/H1ve/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/D0g3-Lab/H1ve/issues)
# Issue Description
run command ```docker-compose -f single.yml up``` or ```docker-compose -f single-nginx.yml up``` happened same question
```
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    app = create_app()
  File "/home/docker/H1ve/CTFd/__init__.py", line 156, in create_app
    upgrade()
  File "/usr/local/lib/python3.7/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 89, in <module>
    run_migrations_online()
  File "migrations/env.py", line 82, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.7/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.7/site-packages/alembic/runtime/migration.py", line 520, in run_migrations
    step.migration_fn(**kw)
  File "/home/docker/H1ve/migrations/versions/b5551cd26764_add_captain_column_to_teams.py", line 32, in upgrade
    op.add_column('teams', sa.Column('captain_id', sa.Integer(), nullable=True))
  File "<string>", line 8, in add_column
  File "<string>", line 3, in add_column
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/ops.py", line 1929, in add_column
    return operations.invoke(op)
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/base.py", line 374, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/toimpl.py", line 132, in add_column
    operations.impl.add_column(table_name, column, schema=schema, **kw)
  File "/usr/local/lib/python3.7/site-packages/alembic/ddl/impl.py", line 237, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/usr/local/lib/python3.7/site-packages/alembic/ddl/impl.py", line 140, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
    compiled,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1060, "Duplicate column name 'captain_id'")
[SQL: ALTER TABLE teams ADD COLUMN captain_id INTEGER]
(Background on this error at: http://sqlalche.me/e/2j85)
```
# Version & Environment
## OS Version
```
Ubuntu 18.04.4 LTS 
```
## Docker-compose Version
```
docker-compose version 1.25.5, build 8a1c60f6
```
## Docker Version
```
Docker version 19.03.8, build afacb8b7f0
```
## Browser Version
```
Microsoft Edge 
Version 81.0.416.72 (Official build) (64-bit)
```

**Comment by Ra6b1t** [comment]
注释掉`migrations/b295b033364d_add_ondelete_cascade_to_foreign_keys.py`文件中的40、41行
```
op.drop_constraint('team_captain_id', 'teams', type_='foreignkey')
op.create_foreign_key('team_captain_id', 'teams', 'users', ['captain_id'], ['id'], ondelete='SET NULL')
```

**Comment by 1476110462** [comment]
您好，我和楼上使用的环境还有错误都是一样的，但是我注释掉还是一样的错误

**Comment by brownfoxsir** [comment]
我也试过了，不起作用，还是一样的错误~~~~

**Comment by vpsru** [comment]
删除掉upgrade()函数

**Comment by 0akarma** [comment]
请等待修复……

**Comment by GaryH4** [comment]
https://github.com/CTFd/CTFd/issues/1411#issuecomment-628981011
mariaDB的问题
修改yml中的mariadb版本为10.4.12

**Comment by 1476110462** [comment]
换了还是不行

**Comment by GaryH4** [comment]
> 换了还是不行

重新compose了吗

**Comment by 1476110462** [comment]
> > 换了还是不行
> 
> 重新compose了吗

对，还是没用，同样的错误

**Comment by GaryH4** [comment]
> > > 换了还是不行
> > 
> > 
> > 重新compose了吗
> 
> 对，还是没用，同样的错误

建议贴出错误日志，以及复现过程，而不只是简短的描述

**Comment by 1476110462** [comment]
> > > > 换了还是不行
> > > 
> > > 
> > > 重新compose了吗
> > 
> > 
> > 对，还是没用，同样的错误
> 
> 建议贴出错误日志，以及复现过程，而不只是简短的描述
师傅，我从centos8换用了centos7，莫名其妙的好了，谢谢师傅，跪谢

**Comment by roshines** [comment]
这个错误修复了嘛。。

**Comment by Tsunami-Song** [comment]
> 
> 
> 删除掉upgrade()函数

删除后继续报错

main_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/runtime/migration.py", line 940, in __init__
main_1   |     self.migration_fn = revision.module.upgrade
main_1   | AttributeError: module 'b5551cd26764_add_captain_column_to_teams_py' has no attribute 'upgrade'

**Comment by brownfoxsir** [comment]
- 删除H1ve目录下的.data隐藏文件夹
- docker-compose.yml down
- 修改single-nginx.yml文件中db的镜像版本为 mariadb:10.4.12
- 重新建立项目
- 大功告成
```shell
sudo rm -rf .data/  

docker-compose -f single-nginx.yml down 

sed -i 's/mariadb:10.4/mariadb:10.4.12/g' single-nginx.yml

docker-compose -f single-nginx.yml up 
```

**Comment by Tsunami-Song** [comment]
Well Done!
在楼上大佬们的帮助下终于搞定了！
https://mp.weixin.qq.com/s?__biz=MzU0NjA1NTc0NQ==&mid=2247483875&idx=1&sn=8f21a628bff94932b4207ddbbe146399&chksm=fb6232cdcc15bbdb10aa0d5e08cd49ec7083c9b7ccf975b4b44179b6bc99f1aefedf6b0422f8&scene=126&sessionid=1590590501&key=1d933e81102b9f193dd06e615e6f471077af4d849f5c45ab9455b894b5c21225beab26f7c71192fc57caf6b49ec4836861f304a87a6e8c4f44d788274f1d889851be44177b48ad9ef76ee7e0db483a63&ascene=1&uin=MzM2OTE2ODg4MA%3D%3D&devicetype=Windows+10+x64&version=62090070&lang=zh_CN&exportkey=A04vA0yieinbqdIlV2AA32U%3D&pass_ticket=z%2FVEeSMfpQH5r0wYhnVHKRR4L%2FwASXu21GFa%2FQEKdF%2BMn2t1ukvSJr1KMaFvGQsx

**Comment by ytvchsy** [comment]
> * 删除H1ve目录下的.data隐藏文件夹
> * docker-compose.yml关闭
> * 修改single-nginx.yml文件中db的版本版本为mariadb：10.4.12
> * 重新建立项目
> * 大功告成

项目可以启动，但是8000端口起不来，进不去……

**Comment by brownfoxsir** [comment]
> > * 删除H1ve目录下的.data隐藏文件夹
> > * docker-compose.yml关闭
> > * 修改single-nginx.yml文件中db的版本版本为mariadb：10.4.12
> > * 重新建立项目
> > * 大功告成
> 
> 项目可以启动，但是8000端口起不来，进不去……
> 
> 

不会呀，我正常启动了呀，你有啥报错信息吗？

**Comment by ytvchsy** [comment]
> > > * 删除H1ve目录下的.data隐藏文件夹
> > > * docker-compose.yml关闭
> > > * 修改single-nginx.yml文件中db的版本版本为mariadb：10.4.12
> > > * 重新建立项目
> > > * 大功告成
> > 
> > 
> > 项目可以启动，但是8000端口起不来，进不去……
> 
> 不会呀，我正常启动了呀，你有啥报错信息吗？

没有报错，输入服务器IP地址加:8000。就无法访问此网站

**Comment by Tsunami-Song** [comment]
> 
> 
> > > > * 删除H1ve目录下的.data隐藏文件夹
> > > > * docker-compose.yml关闭
> > > > * 修改single-nginx.yml文件中db的版本版本为mariadb：10.4.12
> > > > * 重新建立项目
> > > > * 大功告成
> > > 
> > > 
> > > 项目可以启动，但是8000端口起不来，进不去……
> > 
> > 
> > 不会呀，我正常启动了呀，你有啥报错信息吗？
> 
> 没有报错，输入服务器IP地址加:8000。就无法访问此网站

docker ps 看一下正在运行的docker和对应的端口，同时看一下防火墙配置规则

**Comment by brownfoxsir** [comment]
> > > > * 删除H1ve目录下的.data隐藏文件夹
> > > > * docker-compose.yml关闭
> > > > * 修改single-nginx.yml文件中db的版本版本为mariadb：10.4.12
> > > > * 重新建立项目
> > > > * 大功告成
> > > 
> > > 
> > > 项目可以启动，但是8000端口起不来，进不去……
> > 
> > 
> > 不会呀，我正常启动了呀，你有啥报错信息吗？
> 
> 没有报错，输入服务器IP地址加:8000。就无法访问此网站

你用的那个yml文件？single.yml 还是single-nginx.yml？如果用第一个yml文件 你试着关闭防火墙，问题应该能解决

**Comment by ytvchsy** [comment]
> > > > > * 删除H1ve目录下的.data隐藏文件夹
> > > > > * docker-compose.yml关闭
> > > > > * 修改single-nginx.yml文件中db的版本版本为mariadb：10.4.12
> > > > > * 重新建立项目
> > > > > * 大功告成
> > > > 
> > > > 
> > > > 项目可以启动，但是8000端口起不来，进不去……
> > > 
> > > 
> > > 不会呀，我正常启动了呀，你有啥报错信息吗？
> > 
> > 
> > 没有报错，输入服务器IP地址加:8000。就无法访问此网站
> 
> 你用的那个yml文件？single.yml 还是single-nginx.yml？如果用第一个yml文件 你试着关闭防火墙，问题应该能解决

！！！我用的single-nginx.yml，进不去。换了single.yml可以了！！哇…………

**Comment by brownfoxsir** [comment]
> > > > > > * 删除H1ve目录下的.data隐藏文件夹
> > > > > > * docker-compose.yml关闭
> > > > > > * 修改single-nginx.yml文件中db的版本版本为mariadb：10.4.12
> > > > > > * 重新建立项目
> > > > > > * 大功告成
> > > > > 
> > > > > 
> > > > > 项目可以启动，但是8000端口起不来，进不去……
> > > > 
> > > > 
> > > > 不会呀，我正常启动了呀，你有啥报错信息吗？
> > > 
> > > 
> > > 没有报错，输入服务器IP地址加:8000。就无法访问此网站
> > 
> > 
> > 你用的那个yml文件？single.yml 还是single-nginx.yml？如果用第一个yml文件 你试着关闭防火墙，问题应该能解决
> 
> ！！！我用的single-nginx.yml，进不去。换了single.yml可以了！！哇…………

一看你就是在虚拟机中跑的~

**Comment by ytvchsy** [comment]
> > > > > > > * 删除H1ve目录下的.data隐藏文件夹
> > > > > > > * docker-compose.yml关闭
> > > > > > > * 修改single-nginx.yml文件中db的版本版本为mariadb：10.4.12
> > > > > > > * 重新建立项目
> > > > > > > * 大功告成
> > > > > > 
> > > > > > 
> > > > > > 项目可以启动，但是8000端口起不来，进不去……
> > > > > 
> > > > > 
> > > > > 不会呀，我正常启动了呀，你有啥报错信息吗？
> > > > 
> > > > 
> > > > 没有报错，输入服务器IP地址加:8000。就无法访问此网站
> > > 
> > > 
> > > 你用的那个yml文件？single.yml 还是single-nginx.yml？如果用第一个yml文件 你试着关闭防火墙，问题应该能解决
> > 
> > 
> > ！！！我用的single-nginx.yml，进不去。换了single.yml可以了！！哇…………
> 
> 一看你就是在虚拟机中跑的~

你们有没有出现过An Internal Server Error has occurred这个问题。

**Comment by ytvchsy** [comment]
> > > > > > > > * 删除H1ve目录下的.data隐藏文件夹
> > > > > > > > * docker-compose.yml关闭
> > > > > > > > * 修改single-nginx.yml文件中db的版本版本为mariadb：10.4.12
> > > > > > > > * 重新建立项目
> > > > > > > > * 大功告成
> > > > > > > 
> > > > > > > 
> > > > > > > 项目可以启动，但是8000端口起不来，进不去……
> > > > > > 
> > > > > > 
> > > > > > 不会呀，我正常启动了呀，你有啥报错信息吗？
> > > > > 
> > > > > 
> > > > > 没有报错，输入服务器IP地址加:8000。就无法访问此网站
> > > > 
> > > > 
> > > > 你用的那个yml文件？single.yml 还是single-nginx.yml？如果用第一个yml文件 你试着关闭防火墙，问题应该能解决
> > > 
> > > 
> > > ！！！我用的single-nginx.yml，进不去。换了single.yml可以了！！哇…………
> > 
> > 
> > 一看你就是在虚拟机中跑的~
> 
> 你们有没有出现过An Internal Server Error has occurred这个问题。

有什么好的解决方法吗

**Comment by brownfoxsir** [comment]
> > > > > > > > > * 删除H1ve目录下的.data隐藏文件夹
> > > > > > > > > * docker-compose.yml关闭
> > > > > > > > > * 修改single-nginx.yml文件中db的版本版本为mariadb：10.4.12
> > > > > > > > > * 重新建立项目
> > > > > > > > > * 大功告成
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 项目可以启动，但是8000端口起不来，进不去……
> > > > > > > 
> > > > > > > 
> > > > > > > 不会呀，我正常启动了呀，你有啥报错信息吗？
> > > > > > 
> > > > > > 
> > > > > > 没有报错，输入服务器IP地址加:8000。就无法访问此网站
> > > > > 
> > > > > 
> > > > > 你用的那个yml文件？single.yml 还是single-nginx.yml？如果用第一个yml文件 你试着关闭防火墙，问题应该能解决
> > > > 
> > > > 
> > > > ！！！我用的single-nginx.yml，进不去。换了single.yml可以了！！哇…………
> > > 
> > > 
> > > 一看你就是在虚拟机中跑的~
> > 
> > 你们有没有出现过An Internal Server Error has occurred这个问题。
> 
> 有什么好的解决方法吗
> 

你改了啥地方？？？报错了呀…

**Comment by ytvchsy** [comment]
> > > > > > > > > * 删除H1ve目录下的.data隐藏文件夹
> > > > > > > > > * docker-compose.yml关闭
> > > > > > > > > * 修改single-nginx.yml文件中db的版本版本为mariadb：10.4.12
> > > > > > > > > * 重新建立项目
> > > > > > > > > * 大功告成
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 项目可以启动，但是8000端口起不来，进不去……
> > > > > > > 
> > > > > > > 
> > > > > > > 不会呀，我正常启动了呀，你有啥报错信息吗？
> > > > > > 
> > > > > > 
> > > > > > 没有报错，输入服务器IP地址加:8000。就无法访问此网站
> > > > > 
> > > > > 
> > > > > 你用的那个yml文件？single.yml 还是single-nginx.yml？如果用第一个yml文件 你试着关闭防火墙，问题应该能解决
> > > > 
> > > > 
> > > > ！！！我用的single-nginx.yml，进不去。换了single.yml可以了！！哇…………
> > > 
> > > 
> > > 一看你就是在虚拟机中跑的~
> > 
> > 
> > 你们有没有出现过An Internal Server Error has occurred这个问题。
> 
> 有什么好的解决方法吗

没有改动，就是使用中突然间出现这个问题。第一次出现的时候重新启动项目之后，平台成了set up，这一次重新启动之后没啥事了……

**Comment by brownfoxsir** [comment]
好吧！我来填坑了，好几个人问我为什么执行```docker-compose -f single-nginx.yml up```打不开网站，然后我看了看nginx配置，发现nginx缺少配置文件，肯定是存在问题的，解决方式很简单，加配置文件，监听一下域名就好了，至于怎么做不用手把手教了吧~

**Comment by 0akarma** [comment]
默认的配置肯定不行啊😂本来nginx都是给稍微会用的，需要反代的时候才用的

**Comment by yanshu-smile** [comment]
在腾讯云ubuntu 18.04的环境部署的，

我的报错是

sudo docker-compose -f single.yml up


WARNING: The PWD variable is not set. Defaulting to a blank string.
Building main
Step 1/10 : FROM d0g3/h1ve
 ---> 04a6ba2a504a
Step 2/10 : ARG WORKDIR
 ---> Using cache
 ---> 4f72f3b15cb9
Step 3/10 : ENV WORKDIR_IN ${WORKDIR}
 ---> Using cache
 ---> 6dd4729a926c
Step 4/10 : WORKDIR $WORKDIR
ERROR: Service 'main' failed to build : cannot normalize nothing

maridb 10.4.12 我也改了，就是没办法启动
docker的镜像应该是正常的
