### ISSUE TITLE
安装中docker-compose -f single.yml up问题

### ISSUE THREAD

**Issue by YOunGWebER** [D0g3-Lab/H1ve#33]
h1ve_main_1 exited with code 1
main_1   | db is ready
main_1   | Traceback (most recent call last):
main_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
main_1   |     cursor, statement, parameters, context
main_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
main_1   |     cursor.execute(statement, parameters)
main_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
main_1   |     result = self._query(query)
main_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
main_1   |     conn.query(q)
main_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
main_1   |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
main_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
main_1   |     result.read()
main_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1066, in read
main_1   |     first_packet = self.connection._read_packet()
main_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 683, in _read_packet
main_1   |     packet.check_error()
main_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
main_1   |     err.raise_mysql_exception(self._data)
main_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
main_1   |     raise errorclass(errno, errval)
main_1   | pymysql.err.InternalError: (1060, "Duplicate column name 'captain_id'")
main_1   | 
main_1   | The above exception was the direct cause of the following exception:
main_1   | 
main_1   | Traceback (most recent call last):
main_1   |   File "manage.py", line 8, in <module>
main_1   |     app = create_app()
main_1   |   File "/opt/H1ve/CTFd/__init__.py", line 156, in create_app
main_1   |     upgrade()
main_1   |   File "/usr/local/lib/python3.7/site-packages/flask_migrate/__init__.py", line 95, in wrapped
main_1   |     f(*args, **kwargs)
main_1   |   File "/usr/local/lib/python3.7/site-packages/flask_migrate/__init__.py", line 280, in upgrade
main_1   |     command.upgrade(config, revision, sql=sql, tag=tag)
main_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
main_1   |     script.run_env()
main_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
main_1   |     util.load_python_file(self.dir, "env.py")
main_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
main_1   |     module = load_module_py(module_id, path)
main_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 184, in load_module_py
main_1   |     spec.loader.exec_module(module)
main_1   |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
main_1   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
main_1   |   File "migrations/env.py", line 89, in <module>
main_1   |     run_migrations_online()
main_1   |   File "migrations/env.py", line 82, in run_migrations_online
main_1   |     context.run_migrations()
main_1   |   File "<string>", line 8, in run_migrations
main_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
main_1   |     self.get_context().run_migrations(**kw)
main_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/runtime/migration.py", line 520, in run_migrations
main_1   |     step.migration_fn(**kw)
main_1   |   File "/opt/H1ve/migrations/versions/b5551cd26764_add_captain_column_to_teams.py", line 32, in upgrade
main_1   |     op.add_column('teams', sa.Column('captain_id', sa.Integer(), nullable=True))
main_1   |   File "<string>", line 8, in add_column
main_1   |   File "<string>", line 3, in add_column
main_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/operations/ops.py", line 1929, in add_column
main_1   |     return operations.invoke(op)
main_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/operations/base.py", line 374, in invoke
main_1   |     return fn(self, operation)
main_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/operations/toimpl.py", line 132, in add_column
main_1   |     operations.impl.add_column(table_name, column, schema=schema, **kw)
main_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/ddl/impl.py", line 237, in add_column
main_1   |     self._exec(base.AddColumn(table_name, column, schema=schema))
main_1   |   File "/usr/local/lib/python3.7/site-packages/alembic/ddl/impl.py", line 140, in _exec
main_1   |     return conn.execute(construct, *multiparams, **params)
main_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
main_1   |     return meth(self, multiparams, params)
main_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
main_1   |     return connection._execute_ddl(self, multiparams, params)
main_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
main_1   |     compiled,
main_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
main_1   |     e, statement, parameters, cursor, context
main_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
main_1   |     util.raise_from_cause(sqlalchemy_exception, exc_info)
main_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
main_1   |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
main_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
main_1   |     raise value.with_traceback(tb)
main_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
main_1   |     cursor, statement, parameters, context
main_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
main_1   |     cursor.execute(statement, parameters)
main_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
main_1   |     result = self._query(query)
main_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
main_1   |     conn.query(q)
main_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
main_1   |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
main_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
main_1   |     result.read()
main_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1066, in read
main_1   |     first_packet = self.connection._read_packet()
main_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 683, in _read_packet
main_1   |     packet.check_error()
main_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
main_1   |     err.raise_mysql_exception(self._data)
main_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
main_1   |     raise errorclass(errno, errval)
main_1   | sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1060, "Duplicate column name 'captain_id'")
main_1   | [SQL: ALTER TABLE teams ADD COLUMN captain_id INTEGER]
main_1   | (Background on this error at: http://sqlalche.me/e/2j85)

### New Issue Checklist (自检清单)

- [ ] Updated H1ve to the latest version (是否更新到最新版本)
- [ ] I have read the [README](https://github.com/D0g3-Lab/H1ve/blob/master/README.md)
- [ ] I searched for [existing GitHub issues](https://github.com/D0g3-Lab/H1ve/issues)

### Version & Environment (系统/环境版本)
+ Docker Version
![image](https://user-images.githubusercontent.com/49063068/83843058-d01f3480-a736-11ea-9cf0-0480b64330aa.png)

+ Docker-compose Version
![image](https://user-images.githubusercontent.com/49063068/83843088-dc0af680-a736-11ea-8132-c21dc255fed7.png)

+ Os Version
![image](https://user-images.githubusercontent.com/49063068/83843110-e62cf500-a736-11ea-9647-5b7ccea85b8b.png)

+ Browser Version
![image](https://user-images.githubusercontent.com/49063068/83843156-fc3ab580-a736-11ea-9c11-145d4580aa76.png)

**Comment by ssb6666** [comment]
我也遇到了同样的问题，请问你解决了吗

**Comment by radiumtall** [comment]
同问

**Comment by radiumtall** [comment]
https://github.com/D0g3-Lab/H1ve/issues/27

**Comment by YOunGWebER** [comment]
sudo rm -rf .data/  

docker-compose -f single.yml down 

sed -i 's/mariadb:10.4/mariadb:10.4.12/g' single.yml

docker-compose -f single.yml up

**Comment by Anmonce** [comment]
ERROR: Version in "./single.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the services key, or omit the version key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
是因为版本没升级吗？

**Comment by 0akarma** [comment]
这是你的docker-compose版本太低了

**Comment by lvelve404** [comment]
我执行了docker-compose -y single.yml up后一直卡在staring CTFd这里，好长时间都没动了，这是啥情况，求大佬解答
